### ISSUE TITLE
Package installation fails on Node 12

### ISSUE THREAD

**Issue by ConnexJasper** [MayamaTakeshi/sip-mrcp#1]
Installation of the package hangs and never seems to resolve on Node 12 (npm 6.14.16) despite `package.json` claiming support for Node 12,

Reproducible with the following steps:

```
docker run -it node:12-alpine sh
apk add git
mkdir /app
cd /app
npm init -y
npm i sip-mrcp
```

The same set of steps but using `node:16-alpine` works fine.

As a side note, my experience using the package under Node 11 has been fine (other than the install issues - installing under Node 16 but then switching back and running under Node 11, everything works smoothly). If the installation issues could be fixed to enable installing under Node 11 too, that'd be awesome.

Thanks!

**Comment by MayamaTakeshi** [comment]
I could reproduce this with npm@6.7.0

Googling I found people mentioning similar problems. 
One of the recommendations was to update npm.
So I did
```
npm install -g npm@latest
````
and got npm@8.19.2

After that
```
npm install
```
worked on node v12.22.12.

Regarding node 11, it will not work because it is too old and latest npm will not work with it:
```
takeshi@takeshi-desktop:~/src/git/MayamaTakeshi/sip-mrcp$ nvm use 11
Now using node v11.15.0 (npm v)

takeshi@takeshi-desktop:~/src/git/MayamaTakeshi/sip-mrcp$ npm install
ERROR: npm is known not to run on Node.js v11.15.0
You'll need to upgrade to a newer Node.js version in order to use this
version of npm. You can find the latest version at https://nodejs.org/
```
But if you really need it, you might try to find a version of npm that works with node 11 and doesn't hang during package installation.
